[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --class=ProductionSeeder --force && php -S 0.0.0.0:$PORT -t public/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
