[build]
builder = "dockerfile"

[deploy]
# Docker container uses its own entrypoint script
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
DB_CONNECTION = "pgsql"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SANCTUM_STATEFUL_DOMAINS = "greengodelivery-ge-main.vercel.app,localhost,localhost:3000"
# Direct PostgreSQL variables (Railway provides these automatically)
PGHOST = "${{Postgres.PGHOST}}"
PGPORT = "${{Postgres.PGPORT}}"
PGDATABASE = "${{Postgres.PGDATABASE}}"
PGUSER = "${{Postgres.PGUSER}}"
PGPASSWORD = "${{Postgres.PGPASSWORD}}"
