[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan migrate --force && php artisan db:seed --class=ProductionAdminSeeder --force && php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
DB_CONNECTION = "pgsql"
APP_ENV = "production"
APP_DEBUG = "false"
